export const LOAD_ACCOUNTS_REQUEST = 'LOAD_ACCOUNTS_REQUEST'
export const LOAD_ACCOUNTS_SUCCESS = 'LOAD_ACCOUNTS_SUCCESS'
export const LOAD_ACCOUNTS_FAILURE = 'LOAD_ACCOUNTS_FAILURE'

export const ADD_ACCOUNT_REQUEST = 'ADD_ACCOUNT_REQUEST'
export const ADD_ACCOUNT_SUCCESS = 'ADD_ACCOUNT_SUCCESS'
export const ADD_ACCOUNT_FAILURE = 'ADD_ACCOUNT_FAILURE'
