export const OPEN_NOTIFICATION = 'OPEN_NOTIFICATION'
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION'

export const SHOW_INDICATOR = 'SHOW_INDICATOR'
export const HIDE_INDICATOR = 'HIDE_INDICATOR'

export const RESIZE_DEVICE = 'RESIZE_DEVICE'

export const SEARCHING = 'SEARCHING'